-- MySQL Script generated by MySQL Workbench
-- Sun Feb 23 21:03:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema lab2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lab2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table2` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table3` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table4` (
)
ENGINE = InnoDB;

USE `lab2` ;

-- -----------------------------------------------------
-- Table `lab2`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`contact` (
  `Id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `adress` VARCHAR(50) NOT NULL,
  `telephone` CHAR(10) NOT NULL,
  `website` VARCHAR(2083) NULL DEFAULT '',
  `social_media` VARCHAR(2083) NULL DEFAULT '',
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab2`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`restaurant` (
  `Id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `contact_Id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_restaurant_contact1_idx` (`contact_Id` ASC) VISIBLE,
  CONSTRAINT `fk_restaurant_contact1`
    FOREIGN KEY (`contact_Id`)
    REFERENCES `lab2`.`contact` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab2`.`meal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`meal` (
  `Id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dish` VARCHAR(50) NOT NULL,
  `price` INT NOT NULL,
  `gram` INT NOT NULL,
  `restaurantId` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `meal_restaurant` (`restaurantId` ASC) VISIBLE,
  CONSTRAINT `meal_restaurant`
    FOREIGN KEY (`restaurantId`)
    REFERENCES `lab2`.`restaurant` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab2`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`product` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `number_of` SMALLINT NOT NULL,
  `measurement` ENUM('unit', 'kilogram') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab2`.`meal_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`meal_has_product` (
  `meal_Id` SMALLINT UNSIGNED NOT NULL,
  `product_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`meal_Id`, `product_id`),
  INDEX `fk_meal_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_meal_has_product_meal1_idx` (`meal_Id` ASC) VISIBLE,
  CONSTRAINT `fk_meal_has_product_meal1`
    FOREIGN KEY (`meal_Id`)
    REFERENCES `lab2`.`meal` (`Id`),
  CONSTRAINT `fk_meal_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `lab2`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab2`.`regular_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`regular_customer` (
  `Id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `telephone` CHAR(10) NOT NULL,
  `restaurant_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `regularcustomer_restaurant` (`restaurant_id` ASC) VISIBLE,
  CONSTRAINT `regularcustomer_restaurant`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `lab2`.`restaurant` (`Id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab2`.`meal_has_regular customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`meal_has_regular customer` (
  `meal_Id` SMALLINT UNSIGNED NOT NULL,
  `regular customer_Id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`meal_Id`, `regular customer_Id`),
  INDEX `fk_meal_has_regular customer_regular customer1_idx` (`regular customer_Id` ASC) VISIBLE,
  INDEX `fk_meal_has_regular customer_meal1_idx` (`meal_Id` ASC) VISIBLE,
  CONSTRAINT `fk_meal_has_regular customer_meal1`
    FOREIGN KEY (`meal_Id`)
    REFERENCES `lab2`.`meal` (`Id`),
  CONSTRAINT `fk_meal_has_regular customer_regular customer1`
    FOREIGN KEY (`regular customer_Id`)
    REFERENCES `lab2`.`regular_customer` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab2`.`partner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`partner` (
  `Id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nameOfCompany` VARCHAR(50) NOT NULL,
  `type` ENUM('provisioner', 'ads partner', 'supplier of chemistry') NOT NULL,
  `yearsOfCoworking` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab2`.`restaurant_has_partner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`restaurant_has_partner` (
  `restaurant_Id` SMALLINT UNSIGNED NOT NULL,
  `partner_Id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`restaurant_Id`, `partner_Id`),
  INDEX `fk_restaurant_has_partner_partner1_idx` (`partner_Id` ASC) VISIBLE,
  INDEX `fk_restaurant_has_partner_restaurant1_idx` (`restaurant_Id` ASC) VISIBLE,
  CONSTRAINT `fk_restaurant_has_partner_partner1`
    FOREIGN KEY (`partner_Id`)
    REFERENCES `lab2`.`partner` (`Id`),
  CONSTRAINT `fk_restaurant_has_partner_restaurant1`
    FOREIGN KEY (`restaurant_Id`)
    REFERENCES `lab2`.`restaurant` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab2`.`restaurant_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`restaurant_has_product` (
  `restaurant_Id` SMALLINT UNSIGNED NOT NULL,
  `product_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`restaurant_Id`, `product_id`),
  INDEX `fk_restaurant_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_restaurant_has_product_restaurant1_idx` (`restaurant_Id` ASC) VISIBLE,
  CONSTRAINT `fk_restaurant_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `lab2`.`product` (`id`),
  CONSTRAINT `fk_restaurant_has_product_restaurant1`
    FOREIGN KEY (`restaurant_Id`)
    REFERENCES `lab2`.`restaurant` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `lab2`.`worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`worker` (
  `Id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `age` VARCHAR(20) NOT NULL,
  `position` VARCHAR(20) NOT NULL,
  `salary` INT NOT NULL,
  `telephone` CHAR(10) NOT NULL,
  `date_of_employment` DATE NOT NULL,
  `restaurantId` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `worker_restaurant` (`restaurantId` ASC) VISIBLE,
  CONSTRAINT `worker_restaurant`
    FOREIGN KEY (`restaurantId`)
    REFERENCES `lab2`.`restaurant` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
